<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>colonization-swing</artifactId>
    <name>Colonization - Swing</name>
	<description>Colonization game built with Swing</description>
	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
    <!-- Java3D 1.5.2 사용 시 Repository 정보가 필요함 -->
    <!--
	<repositories>
     <repository>
        <id>mvn2s</id>
        <url>https://repo1.maven.org/maven2/</url>
     </repository>
     <repository>
        <id>egovframe</id>
        <url>https://maven.egovframe.go.kr/maven/</url>
     </repository>
     <repository>
        <id>imagej-public</id>
        <url>https://maven.imagej.net/content/repositories/public/</url>
     </repository>
    </repositories>
    -->
    <parent>
        <groupId>org.duckdns.hjow</groupId>
        <artifactId>colonization-java-group</artifactId>
        <version>0.0.1</version>
        <relativePath>../java-mvn/pom.xml</relativePath>
    </parent>
	<dependencies>
		<dependency>
            <groupId>org.duckdns.hjow</groupId>
            <artifactId>hjow-commons</artifactId>
            <version>0.0.32</version>
        </dependency>
        <dependency>
            <groupId>org.duckdns.hjow</groupId>
            <artifactId>colonization-java-common</artifactId>
            <version>0.0.1</version>        
        </dependency>
        <dependency>
            <groupId>org.duckdns.hjow</groupId>
            <artifactId>colonization-java-default</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.duckdns.hjow</groupId>
            <artifactId>colonization-daemon</artifactId>
            <version>0.0.1</version>        
        </dependency>
        <!--
        <dependency>
            <groupId>org.duckdns.hjow</groupId>
            <artifactId>colonization-java-packs</artifactId>
            <version>0.0.1-SNAPSHOT</version>        
        </dependency>
        -->
        <!--
        <dependency>
            <groupId>java3d</groupId>
            <artifactId>j3d-core</artifactId>
            <version>1.5.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>java3d</groupId>
            <artifactId>j3d-core-utils</artifactId>
            <version>1.5.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>java3d</groupId>
            <artifactId>vecmath</artifactId>
            <version>1.5.2</version>
            <scope>provided</scope>
        </dependency>
        -->
        <dependency>
            <groupId>de.sciss</groupId>
            <artifactId>syntaxpane</artifactId>
            <version>1.3.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.6.2</version>
            <scope>provided</scope>
        </dependency>
	</dependencies>
	<build>
        <defaultGoal>install</defaultGoal>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<!--<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>org.duckdns.hjow.colonization.Colonization</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
					<encoding>UTF-8</encoding>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <finalName>${project.artifactId}-${project.version}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <archive>
                        <manifest>
							<addClasspath>false</addClasspath>
							<mainClass>org.duckdns.hjow.colonization.Colonization</mainClass>
						</manifest>
					</archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- license-maven-plugin 는 mvn install 로 자동 구동되지 않는다. mvn license:add-third-party 명령어로 따로 구동해야 한다.  -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>2.7.0</version>
                <configuration>
                    <thirdPartyFilename>LICENSE_THIRD_PARTY.txt</thirdPartyFilename>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                </configuration>
            </plugin>
	    </plugins>
	</build>
</project>