<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.duckdns.hjow</groupId>
  <artifactId>colonization-java-group</artifactId>
  <version>0.0.1</version>
  <packaging>pom</packaging>
  <name>Parent maven project</name>
  <modules>
      <module>../java-api</module>
      <module>../java-common</module>
      <module>../java-defaultpack</module>
      <module>../daemon</module>
      <module>../swing</module>
      <module>../java-web</module>
  </modules>
  <build>
      <defaultGoal>install</defaultGoal>
  </build>
</project>